<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p id="Promises"></p>
    <p id="PromiseState"></p>
    <p> We all make mistakes and also our script can handle errors, Usually a program halts or close abruptly when it encounters an error, so we use
        try catch to avoid the sudden closure of the program
    </p>
    <p>
        there are errors which are purposefully generated to check the logic or whatever the reason it is,
        but further execution of the code must not be stopped and therefore we use try catch
    </p>

    <p>
        try{
            scheduled code
        }
        catch (error){
            console.log("There is some error in the scheduled code")
        }
    </p>

    <p> Custom errors and Error Objects </p>
    <ul> For all the built in errors, the error has some custom properties they are as follows
        <li>name</li>
        <li>message</li>
    </ul>

    <p>The finally clause, is used for the program cleanup</p>
</body>
<script src="20_Try_Catch.js"></script>
</html>